default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tasks_development

test:
  <<: *default
  database: tasks_test

production:
  <<: *default
  database: tasks_production
